### PR TITLE
Calm down Undyne's hair animation

### PR DESCRIPTION
**Pull request by bobsayshilol**
This fixes the hair on Firefox. No idea if it works on Chrome, but don't see why it wouldn't (or how it was working before).

### CODE REVIEW

**Comment by joezeng** [comment]
You had to set it _that_ slow? Wow, TIL.

**Comment by bobsayshilol** [comment]
4 images at 30fps I guess

**Comment by joezeng** [comment]
I feel like it's a bit slow compared to the game. Could you change it to 1/5? Then I'll push it.

**Comment by bobsayshilol** [comment]
Trying 0.2 locally seems too fast in Firefox. Comparing to the first result on google (https://www.youtube.com/watch?v=LSmt92xQ5g8) seems like 4/30 is a much closer match. Are you sure it looks too fast for you?

**Comment by joezeng** [comment]
Huh, you're right, 4/30 is correct.

**Comment by joezeng** [comment]
Somehow I feel like the crazy hair has become a meme of its own by now, but I'll merge it in and see if anybody complains.

**Comment by joezeng** [comment]
(Wow, closing prevents a merge? >_>)

**Pull request merged**
